---
language: python
python: "3.6"
# Use the new container infrastructure
sudo: required
services:
  - docker
# Install ansible
addons:
  apt:
    packages:
      - python-pip
      - git
install:
  # Install ansible
  - pip install ansible
  - >
      git clone
      https://github.com/kewlfft/ansible-aur.git ~/.ansible/plugins/modules/aur
  - docker pull base/archlinux:latest
  - docker run -d -h actual --name actual base/archlinux sleep infinity
  - docker exec actual pacman -Syyu --noconfirm python3
  # Check ansible version
  - ansible --version
script:
  # Basic role syntax check
  - >
      ansible-playbook -i hosts/static
      -t archlinux kubernetes.yml
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
...
