---
language: python
python: "3.6"
# Use the new container infrastructure
sudo: required
services:
  - docker
# Install ansible
addons:
  apt:
    packages:
      - python-pip
install:
  # Install ansible
  - pip install ansible
  - docker run -d base/archlinux sleep infinity
  # Check ansible version
  - ansible --version
script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
...
