---
language: python
python: "3.6"
# Use the new container infrastructure
sudo: required
services:
  - docker
# Install ansible
addons:
  apt:
    packages:
      - python-pip
install:
  # Install ansible
  - pip install ansible
  - docker pull base/archlinux:latest
  - docker run -d -h actual --name actual base/archlinux sleep infinity
  # Check ansible version
  - ansible --version
script:
  # Basic role syntax check
  - >
      ansible-playbook -i hosts/static
      -t archlinux -t install playbooks/kubernetes.yml
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
...
