---
- name: Instantiate the kubernetes hosts.
  hosts: localhost
  tasks:
    - name: Include Terraform role.
      import_role:
        name: terraform
      tags:
        - create
        - terraform
        - destroy
        - teardown
- name: Pre-configure the kubernetes hosts.
  remote_user: root
  gather_facts: "no"
  hosts: kubernetes
  tasks:
    - name: Prepare ArchLinux
      import_role:
        name: archlinux
      tags:
        - create
        - archlinux
    - name: Include kubernetes modules.
      include_role:
        name: ansible.kubernetes-modules
      tags:
        - create
        - kubernetes
- name: Install and run kubernetes.
  hosts: kubernetes
  remote_user: duchess
  tasks:
    - name: Import kubernetes role.
      import_role:
        name: kubernetes
      tags:
        - install
...
# vim: ft=yaml.ansible:
