---
- name: Destroy Linode cluster.
  hosts: localhost
  tasks:
    - name: Include destruction.
      import_role:
        name: tf-destroy
      tags:
        - destroy
- name: Instantiate hosts.
  hosts: localhost
  tags:
    - create
  tasks:
    - name: Include Terraform role.
      import_role:
        name: terraform
- name: Pre-configure the kubernetes hosts.
  remote_user: root
  gather_facts: "no"
  hosts: "{{ orchestrator }}"
  tags:
    - create
    - archlinux
  tasks:
    - name: Prepare ArchLinux
      import_role:
        name: archlinux
- name: Install and run orchestrator.
  hosts: "{{ orchestrator }}"
  remote_user: duchess
  tags:
    - create
    - "{{ orchestrator }}"
  tasks:
    - name: Import orchestrator role.
      import_role:
        name: "{{ orchestrator }}"
- name: Initialize Kubernetes Actual
  hosts: actual
  remote_user: duchess
  tags:
    - kubernetes
  tasks:
    - name: Import Kubernetes Actual
      import_role:
        name: kube-actual
- name: Join Kubernetes Workers
  hosts: workers
  remote_user: duchess
  tags:
    - workers
    - kubernetes
  tasks:
    - name: Import Kubernetes Workers
      import_role:
        name: kube-worker
...
# vim: ft=yaml.ansible
