---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  labels:
    app: jenkins
  namespace: default
  selfLink:
    /apis/extensions/v1beta1/namespaces/default/ingresses/jenkins-ingress
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: jenkins-service
              servicePort: 8080
status:
  loadBalancer: {}
...
