---
- name: Start cluster with terraform.
  terraform:
    project_path: ../tf/kubernetes
    state: present
    force_init: "yes"
  register: kubernetes
  async: 300
  poll: 5
- name: Add hosts to inventory.
  add_host:
    name: "{{ item }}"
    ansible_host: "{{ kubernetes.outputs.addresses.value[index] }}"
    groups:
      - kubernetes
  loop: "{{ kubernetes.outputs.hostnames.value|flatten }}"
  loop_control:
    index_var: index
- name: Wait for SSH connection availability.
  wait_for:
    port: 22
    state: started
    host: "{{ item }}"
  loop: "{{ kubernetes.outputs.addresses.value }}"
...
