---
- name: Start cluster with terraform.
  terraform:
    project_path: ../tf/kubernetes
    state: present
    force_init: "yes"
  register: kubernetes
- name: Add hosts to current inventory.
  add_host:
    name: "{{ item }}"
    group: kubernetes
  loop: "{{ kubernetes.outputs.inventory_hostname.value }}"
- name: Wait for SSH connection availability.
  wait_for:
    port: 22
    state: started
    host: "{{ item }}"
  loop: "{{ kubernetes.outputs.inventory_hostname.value }}"
...
