---
- name: Install the OpenShift API.
  pip:
    name: openshift
    state: latest
  become: "yes"
- name: Run kubeadm init
  shell: kubeadm init --pod-network-cidr=192.168.0.0/16
  become: "yes"
  register: kubeadm
- debug:
    var: kubeadm
- name: Set the join command.
  set_fact:
    join_command: "{{ kubeadm.stdout_lines[-1] }}"
- debug:
    var: join_command
- name: Create kube directory.
  file:
    dest: /home/duchess/.kube
    state: directory
- name: Copy kubeconfig.
  copy:
    src: /etc/kubernetes/admin.conf
    remote_src: "yes"
    dest: /home/duchess/.kube/config
    owner: duchess
    group: docker
  become: "yes"
- name: Copy kubeconfig to local.
  fetch:
    src: /home/duchess/.kube/config
    dest: /root/.kube/config
    flat: "yes"
- name: Apply Calico etcd.
  k8s:
    src: "https://docs.projectcalico.org/\
      v3.2/getting-started/kubernetes/\
      installation/hosted/etcd.yaml"
    state: present
    kubeconfig: /home/duchess/.kube/config
- shell:
    src: "https://docs.projectcalico.org/\
      v3.2/getting-started/kubernetes/\
      installation/rbac.yaml"
    state: present
    kubeconfig: /home/duchess/.kube/config
- shell:
    src: "https://docs.projectcalico.org/\
      v3.2/getting-started/kubernetes/\
      installation/hosted/calico.yaml"
    state: present
    kubeconfig: /home/duchess/.kube/config
...
