---
- name: Install Docker CE
  pacman:
    name: docker
    state: present
  become: "yes"
- name: Create Docker Swarm
  docker_swarm:
    state: present
  register: swarm_leader
  when: inventory_hostname == 'swarm-0'
- debug:
    var: swarm_leader
- name: Add remaining nodes as managers.
  docker_swarm:
    state: join
  when: inventory_hostname != 'swarm-0'
...
