---
- name: Install Docker CE
  pacman:
    name: "{{ item }}"
    state: present
  become: "yes"
  loop:
    - iptables
    - docker
- name: Reboot instance.
  shell: /sbin/shutdown -r +1
  async: 0
  poll: 0
  become: "yes"
- name: Wait for a connection.
  wait_for_connection:
    connect_timeout: 20
    timeout: 900
- name: Start and enable Docker
  service:
    name: docker
    state: started
    enabled: "yes"
  become: "yes"
- name: Install Docker Python module
  pip:
    name: docker
    state: present
  become: "yes"
- name: Create Docker Swarm
  docker_swarm:
    state: present
  register: swarm_leader
  delegate_to: 'swarm-0'
  run_once: "yes"
- debug:
    var: hostvars.swarm-0.ansiblbe_host
  when: inventory_hostname != 'swarm-0'
- debug:
    var: hostvars[item].ansible_host
  loop:
    - swarm-0
    - swarm-1
    - swarm-2
- name: Add remaining nodes as managers
  docker_swarm:
    state: join
    join_token: "{{ swarm_leader.swarm_facts.JoinTokens.Manager }}"
    advertise_addr: "{{ hostvars[inventory_hostname].ansible_host }}"
  when: inventory_hostname != 'swarm-0'
...
