---
- name: Install kubernetes requirements.
  pacman:
    name: ebtables,ethtool,socat
    state: present
  become: "yes"
- name: Install Kubernetes
  aur:
    name: "{{ item }}"
  loop:
    - kubernetes-cni-bin
    - kubelet-bin
    - kubeadm-bin
    - kubectl-bin
- name: Enable Docker
  service:
    name: docker
    state: stopped
    enabled: "yes"
  become: "yes"
- name: Enable kubelet
  service:
    name: kubelet
    enabled: "yes"
    state: stopped
  become: "yes"
- name: Reboot
  shell: /sbin/shutdown -r +1
  async: 0
  poll: 0
  become: "yes"
- name: Wait for a connection
  wait_for_connection:
    connect_timeout: 20
    timeout: 900
- name: Turn swap off.
  shell: swapoff -a
  become: "yes"
...
