---
- name: Execute several modprobes.
  shell: "modprobe -- {{ item }}"
  loop:
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
  become: "yes"
- name: Execute join command.
  shell: "{{ hostvars[groups['actual'][0]].join_command }}"
  become: "yes"
  register: result
- debug:
    var: result
...
