---
- name: Copy configs to master.
  copy:
    src: "{{ item }}"
    dest: /tmp/
  loop:
    - ingress.yml
    - service.yml
    - deployment.yml
- name: Apply Jenkins configs.
  k8s:
    state: present
    src: "/tmp/{{ item }}"
  loop:
    - ingress.yml
    - service.yml
    - deployment.yml
...
