---
- name: Start cluster with terraform.
  terraform:
    project_path: "{{ lookup('env', 'PWD') }}\
      /roles/terraform/files/{{ lookup('env', 'PROJECT') }}"
    state: present
    force_init: "yes"
  register: instances
- name: Add hosts to inventory.
  add_host:
    name: "{{ item }}"
    ansible_host: "{{ instances.outputs.addresses.value[index] }}"
    groups:
      - "{{ lookup('env', 'PROJECT') }}"
  loop: "{{ instances.outputs.hostnames.value|flatten }}"
  loop_control:
    index_var: index
- name: Tag the linodes.
  linode:
    name: "{{ item }}"
    state: tagged
    tags:
      - "{{ lookup('env', 'PROJECT') }}"
  loop: "{{ instances.outputs.hostnames.value|flatten }}"
- name: Tag worker linodes.
  linode:
    name: "{{ item }}"
    state: tagged
    tags:
      - workers
  loop: "{{ instances.outputs.hostnames.value|flatten }}"
  when: item != 'actual'
- name: Wait for SSH connection availability.
  wait_for:
    port: 22
    state: started
    host: "{{ item }}"
  loop: "{{ instances.outputs.addresses.value }}"
...
