---
- name: Start cluster with terraform.
  terraform:
    project_path: "{{ lookup('env', 'PWD') }}\
      /roles/terraform/files/{{ orchestrator }}"
    state: present
    force_init: "yes"
  register: instances
- name: Add hosts to inventory.
  add_host:
    name: "{{ item }}"
    ansible_host: "{{ instances.outputs.addresses.value[index] }}"
    groups:
      - "{{ orchestrator }}"
  loop: "{{ instances.outputs.hostnames.value|flatten }}"
  loop_control:
    index_var: index
- name: Tag the kubernetes master.
  linode:
    name: "{{ item }}"
    state: tagged
    tags:
      - "{{ orchestrator }}"
      - archlinux
  loop: "{{ instances.outputs.hostnames.value|flatten }}"
  when: orchestrator == 'kubernetes'
- name: Tag kubernetes workers.
  linode:
    name: "{{ item }}"
    state: tagged
    tags:
      - workers
  loop: "{{ instances.outputs.hostnames.value|flatten }}"
  when: item != 'actual' and orchestrator == 'kubernetes'
- name: Tag swarm managers.
  linode:
    name: "{{ item }}"
    state: tagged
    tags:
      - archlinux
      - managers
      - swarm
  loop: "{{ instances.outputs.hostnames.value|flatten }}"
  when: orchestrator == 'swarm'
- name: Wait for SSH connection availability.
  wait_for:
    port: 22
    state: started
    host: "{{ item }}"
  loop: "{{ instances.outputs.addresses.value }}"
...
