---
- name: Install kubernetes requirements.
  pacman:
    name: ebtables,ethtool,socat
    state: present
  become: "yes"
- name: Install kubernetes.
  aur:
    name: "{{ item }}"
  loop:
    - kubernetes-cni-bin
    - kubelet-bin
    - kubeadm-bin
    - kubectl-bin
- name: Enable docker service.
  service:
    name: docker
    enabled: "yes"
  become: "yes"
- name: Enable kubelet service.
  service:
    name: kubelet
    enabled: "yes"
  become: "yes"
- name: Restart instance.
  shell: shutdown -r now
  ignore_errors: "yes"
  become: "yes"
# tasks file for kubernetes-actua
- name: Wait for reboot.
  wait_for:
    port: 22
    host: "{{ inventory_hostname }}"
    state: started
- name: Turn swap off.
  shell: swapoff -a
  become: "yes"
- name: Run kubeadm init
  shell: kubeadm init
  become: "yes"
...
