---
- hosts: localhost
  tasks:
    - include_tasks:
        file: tasks/create.yml
        apply:
          tags:
            - create
      tags:
        - create
    - name: Destroy cluster with terraform.
      terraform:
        state: absent
        project_path: ../tf/kubernetes
      tags:
        - destroy
- hosts: kubernetes
  remote_user: root
  roles:
    - {
      role: archlinux,
      tags: [create]
    }
- hosts: kubernetes
  post_tasks:
    - name: Wait for reboot.
      wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        state: started
  roles:
    - {
      role: kubernetes-actual,
      tags: [install]
    }
...
