---
- hosts: localhost
  tasks:
    - include_tasks:
        file: tasks/create.yml
        apply:
          tags:
            - create
      tags:
        - create
    - block:
        - name: Destroy cluster with terraform.
          terraform:
            state: absent
            project_path: ../tf/kubernetes
          tags:
            - destroy
        - meta: end_play
          tags:
            - destroy
- name: Configure the kubernetes hosts.
  hosts: kubernetes
  tasks:
    - include_role:
        name: archlinux
      tags:
        - create
        - archlinux
    - include_role:
        name: ansible.kubernetes-modules
      tags:
        - create
        - kubernetes
- hosts: kubernetes
  remote_user: duchess
  roles:
    - {
      role: kubernetes,
      tags: [install]
    }
...
