---
- name: Instantiate the kubernetes hosts.
  hosts: localhost
  tasks:
    - include_tasks:
        file: tasks/create.yml
        apply:
          tags:
            - create
      tags:
        - create
    - block:
        - name: Destroy cluster with terraform.
          terraform:
            state: absent
            project_path: ../tf/kubernetes
          tags:
            - destroy
          async: 600
          poll: 5
        - meta: end_play
          tags:
            - destroy
    - name: Reset the Cluster
      shell: kubeadm reset -f
      tags:
        - teardown
- name: Pre-configure the kubernetes hosts.
  remote_user: root
  gather_facts: "no"
  hosts: kubernetes
  tasks:
    - name: Prepare ArchLinux
      import_role:
        name: archlinux
      tags:
        - create
        - archlinux
    - name: Include kubernetes modules.
      include_role:
        name: ansible.kubernetes-modules
      tags:
        - create
        - kubernetes
- name: Install and run kubernetes.
  hosts: kubernetes
  remote_user: duchess
  tasks:
    - name: Import kubernetes role.
      import_role:
        name: kubernetes
      tags:
        - install
...
