---
- hosts: localhost
  tasks:
    - include_tasks:
        file: tasks/create.yml
        apply:
          tags:
            - create
      tags:
        - create
    - block:
        - name: Destroy cluster with terraform.
          terraform:
            state: absent
            project_path: ../tf/kubernetes
          tags:
            - destroy
        - meta: end_play
          tags:
            - destroy
- hosts: kubernetes
  roles:
    - {
      role: archlinux,
      tags: [create]
    }
- hosts: kubernetes
  remote_user: duchess
  roles:
    - {
      role: kubernetes,
      tags: [install]
    }
...
