---
- name: Install kubernetes requirements.
  pacman:
    name: ebtables,ethtool,socat
    state: present
  become: "yes"
- name: Install Kubernetes
  aur:
    name: "{{ item }}"
  loop:
    - kubernetes-cni-bin
    - kubelet-bin
    - kubeadm-bin
    - kubectl-bin
  async: 4500
  poll: 5
- name: Enable Docker
  service:
    name: docker
    state: stopped
    enabled: "yes"
  become: "yes"
- name: Enable kubelet
  service:
    name: kubelet
    enabled: "yes"
    state: stopped
  become: "yes"
- name: Reboot immediately if there was a change.
  shell: "sleep 5 && shutdown -r now"
  async: 1
  poll: 0
- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
# - name: Restart instance.
#  reboot:
#    connect_timeout: 60
#  become: "yes"
# - name: Wait for reboot.
#   wait_for:
#    port: 22
#    host: "{{ inventory_hostname }}"
#    state: started
- name: Turn swap off.
  shell: swapoff -a
  become: "yes"
- name: Run kubeadm init
  shell: kubeadm init --pod-network-cidr=192.168.0.0/16
  become: "yes"
...
