---
- name: Install kubernetes requirements.
  pacman:
    name: ebtables,ethtool,netdata,socat
    state: present
  become: "yes"
- name: Install kubernetes.
  aur:
    name: "{{ item }}"
  loop:
    - kubernetes-cni-bin
    - kubelet-bin
    - kubeadm-bin
    - kubectl-bin
- name: Enable services.
  service:
    name: "{{ item }}"
    enabled: "yes"
  become: "yes"
  loop:
    - docker
    - kubelet
    - netdata
- name: Restart instance.
  reboot:
    connect_timeout: 60
    reboot_timeout: 7000
  become: "yes"
- name: Wait for reboot.
  wait_for:
    port: 22
    host: "{{ inventory_hostname }}"
    state: started
- name: Turn swap off.
  shell: swapoff -a
  become: "yes"
- name: Run kubeadm init
  shell: kubeadm init --pod-network-cidr=192.168.0.0/16
  become: "yes"
...
